# Generated by Django 2.0.7 on 2018-08-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyFirstApp', '0002_auto_20180819_0655'),
    ]

    operations = [
        migrations.CreateModel(
            name='logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logscontent', models.CharField(default='', max_length=200)),
                ('createtime', models.DateTimeField(auto_now=True, verbose_name='添加日期')),
            ],
        ),
    ]
